### ISSUE TITLE
При закрытии окна приложение не закрывается

### ISSUE THREAD

**Issue by TheEvilRoot** [danyadev/vk-desktop-app#9]
При закрытии окна приложение остается запущенным, но окно нельзя открыть, нажав на иконку в доке.

Пути решения: при закрытии окна закрывать приложение; сделать пересоздание окна при клике на иконку дока

Система: macOS 10.12.6

**Comment by danyadev** [comment]
При закрытии окна приложение будет закрываться полностью.
